### ISSUE TITLE
playerNameCleaner.js improvements

### ISSUE THREAD

**Issue by leonardp** [agadmator-library/agadmator-library.github.io#1]
MVL's name is misspelled:

https://github.com/agadmator-library/agadmator-library.github.io/blob/7c54e90fb08a9b7ae031e42f38473af267c8735b/build_scripts/playerNameCleaner.js#L87-L88

According to Wikipedia it is "Maxime Vachier-Lagrave"

I also spotted two occurrences of "Paul Charles Morphy" in the database while all other games are listed as "Paul Morphy" only.

Thanks for putting up this project it's really handy :heart: :chess_pawn:

**Comment by agadmator-library** [comment]
Thanks. Fixed that
