### ISSUE TITLE
Both player names

### ISSUE THREAD

**Issue by Manit100** [agadmator-library/agadmator-library.github.io#13]
## Video id or youtube url
https://www.youtube.com/watch?v=kxF8tcA4SI4

## Player white (current)
Tal

## Player black (current)
Flesch (Lvov ): Chapter 1 

## Player white (correct)
Mikhail Tal

## Player black (correct)
János Flesch

## Notes
Both player names should be updated. Youtube video description was unusual, hence the error.

**Comment by agadmator-library** [comment]
Fixed
