### ISSUE TITLE
Both player names

### ISSUE THREAD

**Issue by Manit100** [agadmator-library/agadmator-library.github.io#14]
## Video id or youtube url
https://www.youtube.com/watch?v=EHLOy73imsc

## Player white (current)
Yuliya (ISR) Shvayger

## Player black (current)
Ekaterina (TUR) Atalik

## Player white (correct)
Yuliya Shvayger

## Player black (correct)
Ekaterina Atalik

## Debug notes
Caused by unusual description in Youtube video

**Comment by agadmator-library** [comment]
Fixed
