### ISSUE TITLE
[BUG] UI Issue in the Year and Result column

### ISSUE THREAD

**Issue by snippetkid** [agadmator-library/agadmator-library.github.io#15]
**Describe the bug**
UI Issue in the Year and Result column

**To Reproduce**

1. Go to https://agadmator-library.github.io/
2. Toggle the 'Show result column'
3. UI issue at the 'Year' and 'Result' column

**Expected behavior**
A table should be viewable without any UI issue.

**Screenshots**

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 109.0
 - Resolution: 1920 X 1080

![image](https://user-images.githubusercontent.com/16718733/219714353-cc59924c-b2be-46f8-9268-419c5e0061bb.png)

**Comment by snippetkid** [comment]
Great work with the repo, I'd love to contribute to this. I can raise a PR if that is okay 😄

**Comment by agadmator-library** [comment]
Hey @snippetkid
Thanks for contribution but I had slightly different idea how this should work. In your solution publishedAt column would be present in every device. Right now it is intentionally hidden in smaller screens (same as year column).

I fixed it using by renaming classes.

**Comment by snippetkid** [comment]
Hello 👋 
Thanks for the info, however I think the Year column still has a UI issue. 

![image](https://user-images.githubusercontent.com/16718733/219732570-338fb444-34f6-4631-a2ab-bf1216d9a96c.png)


I think the year column must also have `d-lg-table-cell` class

`yearCell.className = 'd-none d-lg-table-cell'`

**Comment by snippetkid** [comment]
I've added a PR to address the same, would you mind giving it a look and merge it if possible please?

**Comment by agadmator-library** [comment]
You were right. I merged PR.

Big thanks for fix. I'm not a frontend deveoper. My last serious encounter with html and css was at least 10 years ago :)

**Comment by snippetkid** [comment]
Still you've done a great job with this! Thanks for merging my PR, I'm a front-end developer myself and I'd love to keep contributing to this repo 🥂
