### ISSUE TITLE
"Outplayed HARD! || Praggnanandhaa vs Hikaru || Round 11 || FIDE Candidates (2024)" Video has incorrect PGN + player with white

### ISSUE THREAD

**Issue by josephwilliams** [agadmator-library/agadmator-library.github.io#153]
## Video id or youtube url
https://www.youtube.com/watch?v=TpCAKCx5R8w

## Player white (current)
Nijat Abasov

## Player black (current)
Hikaru Nakamura

## Player white (correct)
Praggnanandhaa

## Player black (correct)
Hikaru Nakamura

The correct game PGN can be found here, although with embellished formatting.
https://lichess.org/broadcast/fide-candidates-2024--open/round-11/46ohJ8Qt/k2WUweFl

**Comment by agadmator-library** [comment]
Thanks - changed that
