### ISSUE TITLE
[FEATURE] UI and Theme Update

### ISSUE THREAD

**Issue by snippetkid** [agadmator-library/agadmator-library.github.io#20]
**Is your feature request related to a problem? Please describe.**
Not related to a problem, this is a suggestion for a better UI layout and alignment of controls.

**Describe the solution you'd like**
Attaching a proposed UI as screenshot. This is just a suggestion, please feel free to suggest changes and enhancements as required.

**Major Changes**

1. Added header and moved search bar to top to get more visibility.
2. Moved filters to single row with icons to save a lot of space.
3. Added sort to table headers (supported in bootstrap) to save a lot of space.

![Untitled](https://user-images.githubusercontent.com/16718733/220154245-7ade1a95-ed8f-4358-acfd-605ba0d75220.png)

**Comment by agadmator-library** [comment]
Yeah. I agree that UI needs total rebuild. 
Low handing fruit would be to use some read table solution like dataTables for bootstrap. I will try to do this next. As for filters - right now I have no idea but this UX design looks nice

**Comment by agadmator-library** [comment]
Some templating of html would also be nice. I think that I will just end up learning some frontend framework (like vue.js) and using it here

**Comment by snippetkid** [comment]
Sounds good, if you're considering React, please let me know as I can help you port the whole application to React as I've experience with it.

**Comment by snippetkid** [comment]
Also, if you've liked the UI design, I can contribute towards the front-end development for this. Let me know if you're looking for something like this.

**Comment by agadmator-library** [comment]
As I'm planning to add more filters I reorganized form in different way (with sections)
