### ISSUE TITLE
[FEATURE REQUEST] Add puzzle filter and training video filter

### ISSUE THREAD

**Issue by sk1llsh0t** [agadmator-library/agadmator-library.github.io#26]
1) Add a filter so it shows only puzzle videos where the video just presents a certain position for solving (not full game)
2) Add a filter to show only training videos (i.e. tutorial on the evans gambit, etc)

**Comment by agadmator-library** [comment]
Unfortunately I don't see a way how to extract data for those filters from title, description or video properties.

I think only possibility is to manually categorize videos.

You can play with other filters like title ('puzzle') and max video length but I don't have any other ideas how to solve that.

**Comment by agadmator-library** [comment]
Ad 2
agadmator maintains playlist with tutorials: https://youtube.com/playlist?list=PLDnx7w_xuguES4Oc5fZBVLtKE7u2w_MFJ

**Comment by sk1llsh0t** [comment]
Thanks for the feedback! 

I knew agad had some cartegories already on his channel. i just wasn't sure to what extent. Like the sorcery series or his sagas on different people. of course searching for capablanca will pull all videos in the saga and any extras just as an example.

Anyway, thanks for the tool! Nice work!

**Comment by agadmator-library** [comment]
Thanks. I just wanted to view all videos with certain Player and it evolved
