### ISSUE TITLE
Le Quang Liem currently have two separate names

### ISSUE THREAD

**Issue by justanothernguyen** [agadmator-library/agadmator-library.github.io#29]
Search for "Liem" returned 2 names

![image](https://user-images.githubusercontent.com/1379769/224505708-ca754849-5154-4ced-823b-79a0b235e059.png)

Since there's only one video under the name "Le Quang Liem" it's easier to change to "Quang Liem Le" (and keep using it going forward).

BUT, Liem is a Vietnamese and the proper way to write his name in Vietnamese is "Le Quang Liem" (family name before name).

## Video id or youtube url
https://www.youtube.com/watch?v=8kMFEFeApdg

## Player white (current)
Magnus Carlsen

## Player black (current)
Le Quang Liem

## Player white (correct)
Magnus Carlsen

## Player black (correct)
Quang Liem Le

**Comment by agadmator-library** [comment]
Hi I changed all references to "Le Quang Liem"
