### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by manishKarki358** [agadmator-library/agadmator-library.github.io#41]
really loved your work being a fan of agadmator myself i am also a javascript developer so i wanted to ask you that the chess board that you attached for searching agadmator's video did you really hard coded each and every rule of chess into that board did you get it from somewhere else i mean there are somany things to consider while making working chess board like check ,double check ,en passant ,pawns not moving forward etc so how did you do it

**Comment by agadmator-library** [comment]
Yeah. I'm backend developer (and I know it can be seen from this code) so writing chess board in unfamiliar language would take much more time than I can invest in single side project
