### ISSUE TITLE
Filter by playing moves shows games which don't start by those moves. [BUG]

### ISSUE THREAD

**Issue by HoseynHeydari** [agadmator-library/agadmator-library.github.io#49]
Hi there and here description.

**Describe the bug**
Filter by playing moves shows games that don't match the opening.

**To Reproduce**
1. Click "Game Filters"
2. Click "Filter By Playing Move"
3. Use the mouse to create the game as follows: 1.e4 e5 2.Nf3 d6 3.d4 exd4
4. 12 results will display which [sixth](https://www.youtube.com/watch?v=EwTH8-DsF3w) is irrelevant.

**Expected behavior**
Search results must not include [sixth](https://www.youtube.com/watch?v=EwTH8-DsF3w) game which has no same opening as the game filter specified.

**Screenshots**
![first](https://user-images.githubusercontent.com/15010073/233219073-7792278a-4d98-45b2-b821-7aa3731fb4b3.png)
![second](https://user-images.githubusercontent.com/15010073/233219119-097ec21e-53d3-403a-a590-0a95ab35bba0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Browser Edge
 - Version 112.0.1722.39 (Official Build) (64-bit)

**Additional context**
There is a warning that says:

> This is only a fun project and not everything is properly parsed. Do not trust entirely.

So this is not a problem, but I hope there is an improvement.

**Comment by agadmator-library** [comment]
Hi, there was invalid PGN in video description. Fixed that
