### ISSUE TITLE
year & maybe names - 2 games 1 video re magnus sergey vishy

### ISSUE THREAD

**Issue by nicbentulan** [agadmator-library/agadmator-library.github.io#50]
Thing 1 of 2

Not sure if this counts as an error but because there are 2 games in 1 video this is how it looks like

## Video id or youtube url
[How To Beat Magnus Carlsen?](https://www.youtube.com/watch?v=kbmfcPZliWc)

## Player white (current)
Viswanathan Anand
Magnus Carlsen

## Player black (current)
Magnus Carlsen
Sergey Karjakin

idk did you mean to do really 1 entry for the 2 games?

Thing 2 of 2

oh but there is the matter of the year it currently says just 2014 but it should be both 2014 & 2016?

**Comment by agadmator-library** [comment]
Currently I'm extracting date only for first game in video. This is why only 2014 is displayed and 2016 is missing. I have it on my backlog to fix that.
Each row in table represents single video so if there are more than one game in video player names will be displayed together. I will think about adding some visual divider

**Comment by agadmator-library** [comment]
Hey @nicbentulan 
I did some refactoring and now multiple games are cleary divided in table rows
