### ISSUE TITLE
twitter

### ISSUE THREAD

**Issue by nicbentulan** [agadmator-library/agadmator-library.github.io#51]
it says 'Report missing/invalid data by creating an issue on [GitHub](https://github.com/agadmator-library/agadmator-library.github.io/issues) or by writing [Twitter](https://twitter.com/) post with phrase 'agadmator-library'. Do not forget to add YouTube url'

what's your twitter account please? or did you really mean to make a public tweet that has that phrase and then you have a notification in your email whenever someone tweets something with that phrase?

**Comment by agadmator-library** [comment]
It's a lot more straightforward. From time to time I just search twitter for posts with that phrase. But TBH I don't do that often as everyone is just posting issues on github which is more convenient
