### ISSUE TITLE
Add Morphy head awards to search

### ISSUE THREAD

**Issue by epgeroy** [agadmator-library/agadmator-library.github.io#6]

**Comment by agadmator-library** [comment]
A phrase (case insensitive) "Morphy head" occurs only in 5 videos (description or title).
Adding filter for them would clutter filters section

Videos:
A_AgrNnQMUM
AkE5Z-oy5Mc
axOmdUZgwPs
Oyq2ckjOTUs
w1HZQvx2-MY

**Comment by epgeroy** [comment]
oh, I was not aware. Thank you
