### ISSUE TITLE
White should be Magnus instead of Duda

### ISSUE THREAD

**Issue by Manit100** [agadmator-library/agadmator-library.github.io#9]
** Video id or youtube url **
https://www.youtube.com/watch?v=Tpequut05U0

** Player white (current) **
Jan-Krzysztof Duda

** Player black (current) **
Daniil Dubov

** Result (current) **
White

** Player white (correct) **
Magnus Carlsen

** Player black (correct) **
Daniil Dubov

** Result (correct) **
White

** Notes for debugging **
This error probably resulted from parsing an incorrect description in Agad's Youtube video. Cheers.

**Comment by agadmator-library** [comment]
Thanks - fixed.

It was due to incorrect description. Right now I trust it more than data from chess.com chesstempo.com (as these are derivatives from pgn).
